CaterersPH (Phase 1)

* A platform for caterers to advertise their business and for customers
to find easily the caterers that fit their taste & budget.

Pages
- Home
- About Us
- Contact Us
- How it works
- Privacy & Policy
- Terms and Conditions

Features (Frontsite)	
- Register Account
- Login Account
- Find Caterers
- Find Customers
- Post Services (Caterers)
- Post Jobs (Customers)
- Share Post or Inquiries
- Write/Share Reviews
- In-App Notifications

Database: 

